vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        soiree:
            uri_prefix: /images/soiree
            upload_destination: '%kernel.project_dir%/public/images/soiree'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
